services:
  frontend:
    image: "dilingcloud/gcp.frontend"
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    image: "dilingcloud/gcp.backend"
    ports:
      - "3000:3000"
    depends_on:
      - mongo    
  mongo:
    image: "mongo:4"
    ports:
      - "27017:27017"  
